collections:
  types:
    output: true

defaults:
  - scope:
      path: ""
      type: "types"
    values:
      layout: "type"
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  - scope:
      path: ""
    values:
      layout: "default"
